"""Added details column to Classroom model

Revision ID: ace0f9296cb5
Revises: 
Create Date: 2024-01-30 08:49:17.081322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace0f9296cb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
